// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoundWorldFlightPlanner.Data;

#nullable disable

namespace RoundWorldFlightPlanner.Data.Migrations
{
    [DbContext(typeof(FlightPlannerDbContext))]
    [Migration("20260701142750_AddRunwayPerformanceFields")]
    partial class AddRunwayPerformanceFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("RoundWorldFlightPlanner.Core.Models.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CargoArmM")
                        .HasColumnType("REAL");

                    b.Property<double>("CgAftLimitM")
                        .HasColumnType("REAL");

                    b.Property<double>("CgForwardLimitM")
                        .HasColumnType("REAL");

                    b.Property<double>("CruiseSpeedKts")
                        .HasColumnType("REAL");

                    b.Property<double>("EmptyWeightArmM")
                        .HasColumnType("REAL");

                    b.Property<double>("EmptyWeightKg")
                        .HasColumnType("REAL");

                    b.Property<double>("FuelArmM")
                        .HasColumnType("REAL");

                    b.Property<double>("FuelBurnKgPerHour")
                        .HasColumnType("REAL");

                    b.Property<double>("FuelCapacityKg")
                        .HasColumnType("REAL");

                    b.Property<double>("LandingDistanceFtAtMaxGrossWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxGrossWeightKg")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PilotAndPaxArmM")
                        .HasColumnType("REAL");

                    b.Property<double>("PilotAndPaxWeightKg")
                        .HasColumnType("REAL");

                    b.Property<double>("TakeoffDistanceFtAtMaxGrossWeight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Aircraft");
                });

            modelBuilder.Entity("RoundWorldFlightPlanner.Core.Models.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContinentCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ElevationFt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPavedRunway")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<int>("LongestRunwayFt")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReserveName")
                        .HasColumnType("TEXT");

                    b.Property<int>("SizeClass")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Icao")
                        .IsUnique();

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("RoundWorldFlightPlanner.Core.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SimBriefUsername")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("RoundWorldFlightPlanner.Core.Models.CargoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AcquiredOnLegId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsShippedHome")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWifeOutfit")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AcquiredOnLegId");

                    b.ToTable("CargoItems");
                });

            modelBuilder.Entity("RoundWorldFlightPlanner.Core.Models.FlightLeg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AircraftId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArrivalAirportId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartureAirportId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EngineStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOceanCrossing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LandingUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LayoverDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PlannedCruiseSpeedKts")
                        .HasColumnType("REAL");

                    b.Property<double>("PlannedDistanceNm")
                        .HasColumnType("REAL");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ShutDownUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SimBriefAlternateIcao")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SimBriefFuelPlanKg")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("SimBriefGeneratedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SimBriefRouteText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TakeoffUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TouchdownVerticalSpeedFpm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("ArrivalAirportId");

                    b.HasIndex("DepartureAirportId");

                    b.HasIndex("ItineraryId");

                    b.ToTable("FlightLegs");
                });

            modelBuilder.Entity("RoundWorldFlightPlanner.Core.Models.HappinessEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Delta")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlightLegId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlightLegId");

                    b.HasIndex("ItineraryId");

                    b.ToTable("HappinessEvents");
                });

            modelBuilder.Entity("RoundWorldFlightPlanner.Core.Models.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AircraftId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryGoalPercent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("HappinessScore")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxFlightTimeHours")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.ToTable("Itineraries");
                });

            modelBuilder.Entity("RoundWorldFlightPlanner.Core.Models.CargoItem", b =>
                {
                    b.HasOne("RoundWorldFlightPlanner.Core.Models.FlightLeg", "AcquiredOnLeg")
                        .WithMany()
                        .HasForeignKey("AcquiredOnLegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcquiredOnLeg");
                });

            modelBuilder.Entity("RoundWorldFlightPlanner.Core.Models.FlightLeg", b =>
                {
                    b.HasOne("RoundWorldFlightPlanner.Core.Models.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoundWorldFlightPlanner.Core.Models.Airport", "ArrivalAirport")
                        .WithMany()
                        .HasForeignKey("ArrivalAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoundWorldFlightPlanner.Core.Models.Airport", "DepartureAirport")
                        .WithMany()
                        .HasForeignKey("DepartureAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoundWorldFlightPlanner.Core.Models.Itinerary", "Itinerary")
                        .WithMany("Legs")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("ArrivalAirport");

                    b.Navigation("DepartureAirport");

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("RoundWorldFlightPlanner.Core.Models.HappinessEvent", b =>
                {
                    b.HasOne("RoundWorldFlightPlanner.Core.Models.FlightLeg", "FlightLeg")
                        .WithMany()
                        .HasForeignKey("FlightLegId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RoundWorldFlightPlanner.Core.Models.Itinerary", "Itinerary")
                        .WithMany("HappinessEvents")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightLeg");

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("RoundWorldFlightPlanner.Core.Models.Itinerary", b =>
                {
                    b.HasOne("RoundWorldFlightPlanner.Core.Models.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("RoundWorldFlightPlanner.Core.Models.Itinerary", b =>
                {
                    b.Navigation("HappinessEvents");

                    b.Navigation("Legs");
                });
#pragma warning restore 612, 618
        }
    }
}
